name: startup_news_app
description: Professional swipe-based business news app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  provider: ^6.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  # IMPORTANT: your env is a FILE at assets/env (no extension)
  assets:
    - assets/env
